# Updates frontend on an existing single machine deployment.
- hosts: srv
  roles:
    - frontend_update_on_start
    - swap_enable
    - frontend_deploy
    - swap_disable
    - frontend_update_on_finish
